name: therapylogy
services:
- name: web
  source_dir: /
  github:
    repo: fagundos1/arbon
    branch: master
  run_command: npx serve -s . -l 8080
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"

domains:
- domain: therapylogy.com
  type: PRIMARY
  certificate: auto
- domain: www.therapylogy.com
  type: ALIAS
  certificate: auto

envs:
- key: NODE_ENV
  value: production
  scope: RUN_AND_BUILD_TIME
